### ISSUE TITLE
Could  you open up the entire DASH  framework?

### ISSUE THREAD

**Issue by haitian2du** [kaist-ina/NAS_public#1]
Dear Hyunho Yeo:

         I have read your article carefully recently and think this is a great project!
However, I see that you only open source the NAS-MDSR module. Can you open up the entire framework? I think this will be the most direct and effective way to improve QoE for HAS technology.
I am a student in China and would like to do some research in this area.

Looking forward to your reply!

**Comment by chaos5958** [comment]
Thank you for your attention on our project!

As you mentioned before, we've only released the NAS-MDSR module.
This is due to some intellectual property issue and complex environment setup which requires browser, python server, and Pytorch client together.
I'll discuss with my advisor about let you know soon (<= 1 week).
Even if I can't release all parts, I'll help you about the remaining implementation as best as I can.

**Comment by haitian2du** [comment]
thank you very much!
It was a great surprise for me to receive your reply!
Would you please give me an email address?
My email address is: Dulina@emails.bjut.edu.cn

**Comment by Hgit007** [comment]
Dear Hyunho Yeo:

I also want to do further research based on your research. If you open up the whole project after discussing with your advisor, it will be very exciting for me.

Thank you very much.

**Comment by chaos5958** [comment]
@haitian2du 
My email address is: chaos5958@gmail.com

@haitian2du , @Hgit007 
Sorry to notice you that it would be unavailable to open up remaining parts due to technology transfer issues.
However, I think NAS-MDSR is enough to verify/quantify potential benefits of content-aware video delivery.
There are two remaining parts to run NAS: a) integrated ABR, and b) modified dash.js.
Integrated ABR is built upon Pensieve, which is released on Github, and we only modified state, reward, action, so it would be not that hard to implement it.
dash.js would be a little bit challenging, so I will consider open up this part.

Since I'm busy with other projects, I couldn't working on this right now.
Thus, it could take some time to update this project.
However, I will take any questions and give you information as best as I can.

**Comment by RavaliKolli** [comment]
Hi @chaos5958 will dash.js part would be released anytime sooner? as i am working on something similar i wanted to run the complete flow of your project. Please let me know if it's possible to share those details

**Comment by chaos5958** [comment]
Currently, we cannot expose this implementation due to tech transfer issues. 
I'm really sorry about this, but I can take any questions about implementation difficulty.

**Comment by RavaliKolli** [comment]
Can you provide the steps you followed to build the entire dash framework from scratch if possible?
